apply plugin: 'java-library'

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-webflux'
    api 'org.springframework.cloud:spring-cloud-starter-gateway'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
}
