rootProject.name = 'my-food-to-go-app'

include 'ftgo-common'
include 'ftgo-consumer-service'
include 'ftgo-order-service'
include 'ftgo-order-service-contracts'
include 'ftgo-kitchen-service'
include 'ftgo-kitchen-service-contracts'
include 'ftgo-accounting-service'
include 'ftgo-restaurant-service'
include 'ftgo-delivery-service'
include 'ftgo-service-registry'
include 'ftgo-order-history-service'
include 'ftgo-gateway-common'
include 'ftgo-mobile-gateway'
include 'ftgo-public-gateway'
include 'ftgo-end-to-end-test'
