spring:
  application:
    name: ftgo-accounting-service
  datasource:
    url: jdbc:mysql://localhost:3306/ftgo_accounting
    username: ftgo
    password: ftgo
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: accounting-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

server:
  port: 8084

outbox:
  poll-fixed-delay-ms: 2000
  batch-size: 20
