apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ftgo-gateways
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /mobile(/|$)(.*)
            pathType: ImplementationSpecific
            backend: {service: {name: mobile-gateway, port: {number: 8090}}}
          - path: /public(/|$)(.*)
            pathType: ImplementationSpecific
            backend: {service: {name: public-gateway, port: {number: 8091}}}
