apiVersion: v1
kind: Secret
metadata:
  name: ftgo-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  glitchtip-secret-key: {{ .Values.secrets.glitchtipSecretKey | quote }}
