spring:
  application:
    name: ftgo-consumer-service
  datasource:
    url: jdbc:mysql://localhost:3306/ftgo_consumer
    username: ftgo
    password: ftgo
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
