spring:
  application:
    name: ftgo-restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/ftgo_restaurant
    username: ftgo
    password: ftgo
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085
